version: "3"

services:
  chill-club:
    image: chill_club_image
    container_name: chill_club
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
        - NODE_ENV=development
    volumes:
        - .:/app
        - /app/node_modules